services:
    my-app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        depends_on:
            - my-db
        environment:
            - PORT=3000
            - DATABASE_URL=postgresql://mydbuser:mydbpassword@localhost:5432/mydb?schema=public
    my-db:
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=mydbuser
            - POSTGRES_DB=mydb
            - POSTGRES_PASSWORD=mydbpassword
        volumes:
            - ./postgres-data:/data/db
